from __future__ import annotations

from typing import Final

StrategyId: Final[str] = "baseline.buy_hold"

BASELINE_BUY_HOLD: Final[str] = "baseline.buy_hold"
BASELINE_MOM20_TOP1: Final[str] = "baseline.mom20_top1"
BASELINE_MOM20_EQUAL3: Final[str] = "baseline.mom20_equal3"
BASELINE_MOM20_MA_GATE: Final[str] = "baseline.mom20_ma_gate"
BASELINE_THEME_MOMENTUM: Final[str] = "baseline.theme_momentum"
BASELINE_REGIME_GATED_THEME: Final[str] = "baseline.regime_gated_theme"
ALPHA_SECTOR_LEADERSHIP: Final[str] = "alpha.sector_leadership"
ALPHA_FAMILY_INTENSITY: Final[str] = "alpha.family_intensity"
PORTFOLIO_MOMENTUM_POLICY: Final[str] = "portfolio.momentum_policy"
PORTFOLIO_MOMENTUM_VEHICLE: Final[str] = "portfolio.momentum_vehicle"
PORTFOLIO_MOMENTUM_CONFIDENCE: Final[str] = "portfolio.momentum_confidence"
PORTFOLIO_LEADERSHIP_POLICY: Final[str] = "portfolio.leadership_policy"
PORTFOLIO_LEADERSHIP_CONFIDENCE: Final[str] = "portfolio.leadership_confidence"
PORTFOLIO_LOTTERY_EXPOSURE: Final[str] = "portfolio.lottery_exposure"
PORTFOLIO_TAIL_CONCENTRATION: Final[str] = "portfolio.tail_concentration"
PORTFOLIO_CONVEXITY_HOLD: Final[str] = "portfolio.convexity_hold"
PORTFOLIO_CONVEXITY_REBALANCE: Final[str] = "portfolio.convexity_rebalance"
PORTFOLIO_CONVEXITY_VARIANT: Final[str] = "portfolio.convexity_variant"
PORTFOLIO_LOTTERY_REBALANCE: Final[str] = "portfolio.lottery_rebalance"
STICKY_LEADER_BASE: Final[str] = "sticky.leader_base"
STICKY_IMPULSE_CRASH: Final[str] = "sticky.impulse_crash"
STICKY_FAMILY_PEAK_LOCK: Final[str] = "sticky.family_peak_lock"
STICKY_SPLIT_FILL_LOCK: Final[str] = "sticky.split_fill_lock"
STICKY_MOM60_PEAK_LOCK: Final[str] = "sticky.mom60_peak_lock"
STICKY_HOUSE_MONEY: Final[str] = "sticky.house_money"
STICKY_MOM60_CONCENTRATED: Final[str] = "sticky.mom60_concentrated"
STICKY_MOM60_RAW: Final[str] = "sticky.mom60_raw"
STICKY_MOM60_HOLD: Final[str] = "sticky.mom60_hold"
STICKY_MOM60_ABS_CASH: Final[str] = "sticky.mom60_abs_cash"
STICKY_EQUITY_MOM60: Final[str] = "sticky.equity_mom60"
STICKY_EQUITY_MOM60_VOL: Final[str] = "sticky.equity_mom60_vol"
